# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_data_gen_0_0/design_1_adc_data_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adc_data_gen_0_0 || ORIG_REF_NAME==design_1_adc_data_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_adc_interface_fft_vco_0_0/design_1_adc_interface_fft_vco_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_adc_interface_fft_vco_0_0 || ORIG_REF_NAME==design_1_adc_interface_fft_vco_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vco_interface_0_0/design_1_vco_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vco_interface_0_0 || ORIG_REF_NAME==design_1_vco_interface_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xfft_0_0 || ORIG_REF_NAME==design_1_xfft_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_0 || ORIG_REF_NAME==design_1_floating_point_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_2_0/design_1_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_2_0 || ORIG_REF_NAME==design_1_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_1_0/design_1_floating_point_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_floating_point_1_0 || ORIG_REF_NAME==design_1_floating_point_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_2_0/design_1_floating_point_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_floating_point_2_0 || ORIG_REF_NAME==design_1_floating_point_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_0_0/design_1_AND_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_0_0 || ORIG_REF_NAME==design_1_AND_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_0_1/design_1_AND_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_0_1 || ORIG_REF_NAME==design_1_AND_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AND_0_2/design_1_AND_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AND_0_2 || ORIG_REF_NAME==design_1_AND_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_floating_point_3_0/design_1_floating_point_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_floating_point_3_0 || ORIG_REF_NAME==design_1_floating_point_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_3_0/design_1_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_3_0 || ORIG_REF_NAME==design_1_xlconstant_3_0} -quiet] -quiet

# XDC: /home/selaka/selaka_deemantha/SELAKA/UNI/FYP/fft_log_ieee_calculation/simulation_project/project_1/project_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
